/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */
public class Mostrar extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();// modelo de tabla
    private int renglon = -1;
    private String codigoEncontrado = "";

    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        try {
            initComponents();
            setClosable(true); // boton para cerrar ventanas
            setDefaultCloseOperation(DISPOSE_ON_CLOSE); //CIERRA MEJOR QUE EL THIS.HIDE();

            String[] titulos = {"Codigo", "Nombre", "Correo", "Telefono", "Edad"};
            modelo = new DefaultTableModel(null, titulos);//asignar objeto modelo a la tabla
            Tabla.setModel(modelo);
            CargarArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CargarArchivo() throws IOException {

        try {
            BufferedReader leer = new BufferedReader(new FileReader("Agenda.txt"));
            String renglon = "";
            String aux = "";
            while ((renglon = leer.readLine()) != null) {
                String[] datos = renglon.split(" _ ");//separar los datos por la condicion
                String c = datos[0];// asignar valor con la posicion del split
                String n = datos[1];
                String co = datos[2];
                String t = datos[3];
                String e = datos[4];
                modelo.addRow(new Object[]{c, n, co, t, e}); //asignar valor a la tabla
                Tabla.setModel(modelo);

            }
            leer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(394, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(10, 168));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(394, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(1, 1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel5.add(jScrollPane1);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (renglon == -1) {
            JOptionPane.showMessageDialog(null, "Elige una fila");
        } else {
            BufferedReader leer = null;//sirve para abrir un archivo para leerlo
            try {
                FileWriter archivo = new FileWriter("auxiliar.txt");
                JOptionPane.showMessageDialog(null, codigoEncontrado);
                leer = new BufferedReader(new FileReader("Agenda.txt"));
                String renglon = "";
                String aux = "";
                while ((renglon = leer.readLine()) != null) {
                    //aux += renglon+ "\n";
                    if (renglon.length() != 0) {
                        String[] partes = renglon.split(" _ ");
                        if (codigoEncontrado.equals(partes[0])) {

                        } else {
                            // JOptionPane.showMessageDialog(null, partes[0]);
                            archivo.write(partes[0] + " _ " + partes[1] + " _ " + partes[2] + " _ " + partes[3] + " _ " + partes[4] + "\n");

                        }
                    }
                }
                archivo.close();
                leer.close();

                File arg = new File("Agenda.txt");
                File arg2 = new File("auxiliar.txt");
                Path original = Paths.get("auxiliar.txt");
                Path modificar = Paths.get("Agenda.txt");
                if (arg.exists() && arg2.exists()) {
                    //arg.delete();
                    Files.move(original, modificar, StandardCopyOption.REPLACE_EXISTING);
                }
                //JOptionPane.showMessageDialog(null, aux);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    leer.close();
                } catch (IOException ex) {
                    Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMousePressed
        //metodo para saber la fila seleccionada 
        renglon = Tabla.getSelectedRow();

        if (renglon == -1) {
            JOptionPane.showMessageDialog(null, "Elige una fila");
        } else {
            Tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {//Metodo abstracto
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    codigoEncontrado = Tabla.getValueAt(renglon, 0).toString();//igualar la variable a la communa 0 de la opcion seleccionada
                    //JOptionPane.showMessageDialog(null, "Codigo: " + codigoEncontrado);
                }

            });
        }
    }//GEN-LAST:event_TablaMousePressed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (renglon == -1) {
            JOptionPane.showMessageDialog(null, "Elige una fila");
        } else {
            BufferedReader leer = null;
            try {
                FileWriter archivo = new FileWriter("auxiliar.txt");
                JOptionPane.showMessageDialog(null, codigoEncontrado);
                leer = new BufferedReader(new FileReader("Agenda.txt"));
                String renglon = "";
                String aux = "";
                while ((renglon = leer.readLine()) != null) {
                    //aux += renglon+ "\n";
                    if (renglon.length() != 0) {
                        String[] partes = renglon.split(" _ ");
                        if (codigoEncontrado.equals(partes[0])) {
                            String co = JOptionPane.showInputDialog("Escribe el codigo");
                            String nom = JOptionPane.showInputDialog("Escribe el nombre");
                            String cor = JOptionPane.showInputDialog("Escribe el correo");
                            String tel = JOptionPane.showInputDialog("Escribe el telefono");
                            String ed = JOptionPane.showInputDialog("Escribe la edad");
                            nom = nom.toUpperCase();
                            cor = cor.toLowerCase();
                            archivo.write(co+ " _ " +nom+ " _ " +cor+ " _ " +tel+ " _ " +ed+"\n");
                        } else {
                            // JOptionPane.showMessageDialog(null, partes[0]);
                            archivo.write(renglon + "\n");

                        }
                    }
                }
                archivo.close();
                leer.close();

                File arg = new File("Agenda.txt");
                File arg2 = new File("auxiliar.txt");
                Path original = Paths.get("auxiliar.txt");
                Path modificar = Paths.get("Agenda.txt");
                if (arg.exists() && arg2.exists()) {
                    //arg.delete();
                    Files.move(original, modificar, StandardCopyOption.REPLACE_EXISTING);
                }
                //JOptionPane.showMessageDialog(null, aux);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    leer.close();
                } catch (IOException ex) {
                    Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }


    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
